
- hosts: all
  become: yes
  become_user: root
  gather_facts: false
  vars:
    tomcat_group: tomcat
    tomcat_user: tomcat
    http_port: 8080
    https_port: 8443
  handlers:
    - name: "restart tomcat"
      service: name=tomcat state=restarted

  tasks:
    - name: "Install Java 11"
      apt: name=openjdk-11-jre-headless state=present

    - name: "update packages"
      apt:
       update_cache: yes

    - name: "add group tomcat"
      group:
        name={{tomcat_group}}

    - name: "add user tomcat"
      user:
        name={{tomcat_user}} 
        group={{tomcat_group}} 
        home=/usr/share/tomcat 
        createhome=no
      become: True
      become_method: sudo

    - name: "Download Tomcat"
      get_url: url=https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.13/bin/apache-tomcat-10.1.13.tar.gz dest=/opt/apache-tomcat-10.1.13.tar.gz

    - name: "Extract archive"
      command: chdir=/usr/share /bin/tar xvf /opt/apache-tomcat-10.1.13.tar.gz -C /opt/ creates=/opt/apache-tomcat-10.1.13

    - name: "Symlink install directory"
      file: src=/opt/apache-tomcat-10.1.13 path=/usr/share/tomcat state=link

    - name: "Change ownership of Tomcat installation"
      file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

    - name: "Configure Tomcat server"
      template: src=~/maven-ansible-project/roles/tomcat/templates/server.xml dest=/usr/share/tomcat/conf/


    - name: "Create  sample directory"
      file:
        path: "/opt/apache-tomcat-10.1.13/webapps/samples"
        state: directory
        mode: 0777



    - name: "copy war file"
      copy: src=~/maven-ansible-project/target/SampleServlet.war dest=/opt/apache-tomcat-10.1.13/webapps/


      notify: restart tomcat


    - name: "Install Tomcat init script"
      copy: src=~/maven-ansible-project/roles/tomcat/files/tomcat.service dest=/etc/systemd/system mode=0755

    - name: restart tomcat
      systemd:
        state: restarted
        daemon_reload: yes
        name: tomcat

    - name: "Start Tomcat"
      service: name=tomcat state=started enabled=yes




    - name: "wait for tomcat to start"
      wait_for: port={{http_port}}
